-record(sna_header, {
    i        :: byte(),
    r        :: byte(),
    af       :: non_neg_integer(),
    bc       :: non_neg_integer(),
    de       :: non_neg_integer(),
    hl       :: non_neg_integer(),
    ix       :: non_neg_integer(),
    iy       :: non_neg_integer(),
    af_alt   :: non_neg_integer(),
    bc_alt   :: non_neg_integer(),
    de_alt   :: non_neg_integer(),
    hl_alt   :: non_neg_integer(),
    sp       :: non_neg_integer(),
    iff2     :: byte(),
    im       :: byte(),
    border   :: byte(),
    mem      :: binary(),
    is_128k  :: boolean(),
    pc       :: integer() | undefined,
    p7ffd    :: byte() | undefined,
    ay_flag  :: byte() | undefined,
    raw_extra :: binary() | undefined
}).
