-record(z80_header, {
    version = 1  :: 1 | 2 | 3,
    a            :: byte(),
    f            :: byte(),
    bc           :: non_neg_integer(),
    de           :: non_neg_integer(),
    hl           :: non_neg_integer(),
    pc           :: non_neg_integer(),
    sp           :: non_neg_integer(),
    i            :: byte(),
    r            :: byte(),
    border       :: byte(),
    bc_alt       :: non_neg_integer(),
    de_alt       :: non_neg_integer(),
    hl_alt       :: non_neg_integer(),
    a_alt        :: byte(),
    f_alt        :: byte(),
    ix           :: non_neg_integer(),
    iy           :: non_neg_integer(),
    iff1         :: byte(),
    iff2         :: byte(),
    im           :: byte(),
    hw_mode      :: byte(),
    p7ffd        :: byte(),
    mem          :: binary(),
    pages        :: #{non_neg_integer() => binary()}
}).
